In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [3]:
iris = load_iris()

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
df = pd.DataFrame(iris.data, columns= iris.feature_names)
df['target'] = iris.target

In [10]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [11]:
df.sample(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
58                 6.6               2.9                4.6               1.3   
125                7.2               3.2                6.0               1.8   

     target  
58        1  
125       2

In [12]:
df.target.unique()

array([0, 1, 2])

In [13]:
df.target.unique()

array([0, 1, 2])

In [14]:
## split data
X = df.iloc[:,:-1]
y = df.iloc[:, -1]

## test train split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.20, random_state=111)

In [15]:
## Model training
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

In [16]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [17]:
y_pred = classifier.predict(X_test)

In [18]:
y_pred

array([0, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 0, 1, 2, 2, 0, 2, 1, 0, 2, 1, 2,
       1, 1, 2, 0, 0, 2, 0, 2])

In [21]:
classifier.predict_proba(X_test) ## by default skleatn assumes 0.5 as threshold value

array([[9.68916346e-01, 3.10835534e-02, 1.00752360e-07],
       [9.64598514e-01, 3.54012034e-02, 2.83072983e-07],
       [9.42911142e-07, 5.04122871e-03, 9.94957828e-01],
       [8.20126023e-04, 4.36307332e-01, 5.62872542e-01],
       [7.38089397e-04, 4.75498785e-01, 5.23763126e-01],
       [9.48263900e-01, 5.17354588e-02, 6.41055379e-07],
       [9.78014684e-01, 2.19852603e-02, 5.58332821e-08],
       [5.71664243e-05, 9.75126923e-02, 9.02430141e-01],
       [5.90844406e-06, 1.22405314e-02, 9.87753560e-01],
       [4.53909113e-03, 6.49356620e-01, 3.46104289e-01],
       [8.65449973e-07, 1.28384611e-02, 9.87160673e-01],
       [9.72976153e-01, 2.70238077e-02, 3.90582420e-08],
       [6.02857267e-04, 5.66720897e-01, 4.32676245e-01],
       [1.83376919e-05, 3.59023802e-02, 9.64079282e-01],
       [1.16628385e-07, 6.15075285e-03, 9.93849131e-01],
       [9.85373971e-01, 1.46259494e-02, 7.92581839e-08],
       [1.42874289e-03, 4.79075798e-01, 5.19495459e-01],
       [1.51934557e-01, 8.44935

In [22]:
### Evaluation matrices
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [23]:
confusion_matrix(y_test, y_pred)

array([[10,  0,  0],
       [ 0,  5,  2],
       [ 0,  1, 12]])

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      0.71      0.77         7
           2       0.86      0.92      0.89        13

    accuracy                           0.90        30
   macro avg       0.90      0.88      0.89        30
weighted avg       0.90      0.90      0.90        30



In [25]:
from sklearn.metrics import roc_curve, auc, roc_auc_score

In [26]:
y_pred_proba = classifier.predict_proba(X_test)[:,1]

In [27]:
y_pred_proba

array([0.03108355, 0.0354012 , 0.00504123, 0.43630733, 0.47549878,
       0.05173546, 0.02198526, 0.09751269, 0.01224053, 0.64935662,
       0.01283846, 0.02702381, 0.5667209 , 0.03590238, 0.00615075,
       0.01462595, 0.4790758 , 0.84493526, 0.01993562, 0.02284337,
       0.85265275, 0.11568629, 0.84951945, 0.95249802, 0.19271021,
       0.0557636 , 0.05955747, 0.38920027, 0.01797395, 0.01547767])

In [29]:
#fpr, tpr, threshold = roc_curve(y_test, y_pred_proba)

In [30]:
#threshold

In [31]:
#fpr

In [32]:
#tpr

In [33]:
#roc_auc = auc(fpr, tpr)

In [34]:
#plt.figure(figsize=(8,6))
#plt.plot(fpr, tpr)

In [35]:
#roc_auc

In [36]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import KFold

In [37]:
cv = KFold(n_splits=5)

In [38]:
from sklearn.model_selection import cross_val_score

In [40]:
#scores = cross_val_score(classifier, X_train, y_train, cv= cv, scoring= 'accuracy')

In [42]:
#np.mean(scores)

In [43]:
#scores